// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, Ensemble, Itemerge, care, more, polyglot, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require('underscore');

  Backbone = require('backbone');

  Itemerge = require('./itemerge');

  polyglot = require('upon').polyglot;

  care = require('there').care;

  more = require('there').more;

  Ensemble = (function(_super) {

    __extends(Ensemble, _super);

    function Ensemble() {
      return Ensemble.__super__.constructor.apply(this, arguments);
    }

    Ensemble.prototype.model = Itemerge;

    Ensemble.prototype.inits = {
      planets: {
        the: [["Η", 25, 108, "MO", 1, "☽", "Asklēpios", "Selēnē", "Moon"], ["Ε", 20, 76, "ME", 2, "☿", "Hermēs", "Hermēs", "Mercury_(planet)"], ["Ι", 8, 82, "VE", 3, "♀", "Anubio", "Aphrodite", "Venus"], ["Ω", 19, 120, "SO", 0, "☉", "Nechepsō & Petosiris", "Hēlios", "Sun"], ["Α", 15, 66, "MA", 4, "♂", "Abramos", "Arēs", "Mars"], ["Υ", 12, 79, "JU", 5, "♃", "Orpheus", "Zeus", "Jupiter"], ["Ο", 30, 57, "SA", 6, "♄", "Kritodēmos", "Kronos", "Saturn"]],
        add: {
          traits: ["traditional", "planet", "dispositor", "index"]
        },
        attributes: {
          key: "id",
          use: {
            "id": 3,
            "sid": 4,
            "u": 5,
            "name": null,
            "minor": 1,
            "major": 2,
            "wid": 8
          },
          related: {
            "vowel": 0,
            "founder": 6,
            "phonetic": 7
          }
        }
      },
      dispositors: {
        the: [["NN", "☊", 11], ["SN", "☋", null]],
        add: {
          traits: ["dispositor"]
        },
        attributes: {
          key: "id",
          use: {
            id: 0,
            u: 1,
            name: null,
            sid: 2
          }
        }
      },
      angles: {
        the: [["AS", "⇠"], ["MC", "⇡"], ["DS", "⇢"], ["IC", "⇣"]],
        add: {
          traits: ["angle"]
        },
        attributes: {
          key: "id",
          use: {
            id: 0,
            u: 1,
            name: null
          }
        }
      },
      outers: {
        the: [["UR", "♅", 7, "Uranus"], ["NE", "♆", 8, "Neptune"], ["PL", "♇", 9, "Pluto"]],
        add: {
          traits: ["modern", "outer", "planet", "index"]
        },
        attributes: {
          key: "id",
          use: {
            id: 0,
            sid: 2,
            u: 1,
            wid: 3,
            name: null
          }
        }
      },
      further: {
        the: [[15, "Chiron", "\u26B7", "2060_Chiron"], [17, "Ceres", "\u26B3", "Ceres_(dwarf_planet)"], [18, "Pallas", "\u26B4", "2_Pallas"], [19, "Juno", "\u26B5", "3_Juno"], [20, "Vesta", "\u26B6", "4_Vesta"]],
        add: {
          traits: ["modern", "index"]
        },
        attributes: {
          key: "id",
          use: {
            id: 1,
            sid: 0,
            wid: 3,
            name: null
          }
        }
      },
      utility: {
        the: [["-", "Use through `@getNone`."], ["!", "Use through `@getError`."], ["?", "Use through `@getUnknown`."]],
        add: {
          traits: []
        },
        attributes: {
          key: "id",
          use: {
            id: 0,
            note: 1,
            name: null
          }
        }
      }
    };

    Ensemble.prototype.words = {
      expect: ["name"],
      filler: ["id"],
      data: {
        "-": {
          name: {
            en: [true, "None"],
            bg: [true, "Няма"]
          }
        },
        "!": {
          name: {
            en: [true, "Error"],
            bg: [true, "Грешка"]
          }
        },
        "?": {
          name: {
            en: [true, "Unknown"],
            bg: [true, "Незнайно"]
          }
        }
      }
    };

    Ensemble.prototype.initialize = function(models, cosmos) {
      var add, attributes, e, init, item, key, value, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      this.cosmos = cosmos;
      if (this.cosmos != null) {
        this.school = (_ref = this.cosmos.school) != null ? _ref : null;
        this.language = (_ref1 = this.cosmos.language) != null ? _ref1 : null;
      }
      _.extend(this.words.data, care);
      for (key in more) {
        add = more[key];
        if (this.inits[key] != null) {
          this.inits[key].the = _.union(this.inits[key].the, add);
        }
      }
      _.extend(this, polyglot.ensure);
      if (!this.translatable(_.values(this.inits))) {
        throw "Itemerge stuff can't be named!";
      }
      e = [];
      _ref2 = _.values(this.inits);
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        init = _ref2[_i];
        _ref3 = init.the;
        for (_j = 0, _len1 = _ref3.length; _j < _len1; _j++) {
          item = _ref3[_j];
          attributes = {};
          _ref4 = init.attributes.use;
          for (key in _ref4) {
            value = _ref4[key];
            attributes[key] = item[value];
          }
          _ref5 = init.add;
          for (key in _ref5) {
            value = _ref5[key];
            attributes[key] = value;
          }
          e.push(attributes);
        }
      }
      this.reset(e);
      return this;
    };

    Ensemble.prototype.id = function(id) {
      var _ref;
      return (_ref = this.get(id)) != null ? _ref : this.getUnknown();
    };

    Ensemble.prototype.sid = function(id) {
      var found;
      found = this.find(function(item) {
        return ("" + (item.get('sid'))) === ("" + id);
      });
      return found != null ? found : this.getUnknown();
    };

    Ensemble.prototype.planets = function() {
      return new Backbone.Collection(this.filter(function(item) {
        return _.include(item.attributes.traits, 'planet');
      }));
    };

    Ensemble.prototype.seven = function() {
      return new Backbone.Collection(this.filter(function(item) {
        return _.include(item.attributes.traits, 'traditional');
      }));
    };

    Ensemble.prototype.dispositors = function() {
      return new Backbone.Collection(this.filter(function(item) {
        return _.include(item.attributes.traits, 'dispositor');
      }));
    };

    Ensemble.prototype.index = function() {
      return new Backbone.Collection(this.filter(function(item) {
        return _.include(item.attributes.traits, 'index');
      }));
    };

    Ensemble.prototype.getNone = function() {
      return this.get("-");
    };

    Ensemble.prototype.getError = function() {
      return this.get("!");
    };

    Ensemble.prototype.getUnknown = function() {
      return this.get("?");
    };

    return Ensemble;

  })(Backbone.Collection);

  module.exports = Ensemble;

}).call(this);
